"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Product_1 = require("./Product");
const productManager_1 = require("./productManager");
let laptop = new Product_1.Product("Laptop", 20000000);
let iphone = new Product_1.Product("Iphone", 17000000);
let productmanager = new productManager_1.ProductManager();
productmanager.add(laptop);
productmanager.add(iphone);
console.log(productmanager.getAll());
