"use strict";
exports.__esModule = true;
var Employee_1 = require("./Employee");
var EmployeeManager_1 = require("./EmployeeManager");
var employee1 = new Employee_1.Employee('Ngo', 'Minh Ngoc', new Date('1993/11/17'), 'Ba Dinh', 'Staff', '1');
var employee2 = new Employee_1.Employee('Pham', 'Thanh Thao', new Date('1995/5/15'), 'Ha Dong', 'Manager', '2');
var employee3 = new Employee_1.Employee('Tran', 'Anh Kiet ', new Date('2000/9/28'), 'Quang Nom', 'Security', '3');
var employeeManager = new EmployeeManager_1.EmployeeManager();
console.log(employee1);
employeeManager.addEmmployee(employee1);
employeeManager.addEmmployee(employee2);
employeeManager.addEmmployee(employee3);
console.log(employeeManager.getInfo());
employeeManager["delete"]('1');
console.log(employeeManager.getInfo());
