"use strict";
exports.__esModule = true;
var BinaryTree_1 = require("./src/BinaryTree");
var tree = new BinaryTree_1.BinaryTree();
tree.insert(5);
tree.insert(6);
tree.insert(7);
tree.insert(8);
tree.insert(3);
tree.insert(4);
console.log('The number of nodes ' + tree.totalNode);
tree.inorder(tree.root);
